"""empty message

Revision ID: 2306ccfffda9
Revises: 
Create Date: 2020-09-29 03:39:11.738786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2306ccfffda9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_word', sa.String(), nullable=True),
    sa.Column('dari_translate', sa.String(), nullable=True),
    sa.Column('pashto_translate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_words')
    op.drop_table('logins')
    op.drop_table('books')
    # ### end Alembic commands ###
